README.md, zabbix_auto_config/processing.py, zabbix_auto_config/utils.py
The [details parameter is required](https://www.zabbix.com/documentation/5.0/manual/api/reference/hostinterface/object) for SNMP interfaces in v5.  When creating an SNMP interface and no details are passed, default to a SNMPv2c interface utilizing the `{$SNMP_COMMUNITY}` macro.
=> Fix SNMP interface creation on Zabbix API v5.

.gitignore, README.md, config.sample.ini, zabbix.template.yaml
Fixes #21
Tested with the new podman 3.0.1. I'm fairly sure only the current podman 2.2.x series is bugged when using play kube.
=> Update quickstart/Don't use decommissioned container image

config.sample.ini, zabbix_auto_config/processing.py, zabbix_auto_config/utils.py
This is related to #23
This PR tries to be readable, maintainable and configurable. It also logs when host tags are changed. Only tag names that start with the new config value `tags_prefix` will be touched/synchronized.
Note regarding tags: Tags in Zabbix are name/value pairs. Names are not unique, but the name/value combination must be unique.
Zabbix internally uses objects like `{"tag": "foo", "value": "123"}`, but this PR uses a simpler `["foo", "123"]` object.
=> Add ability to tag hosts

README.md, config.sample.ini, zabbix_auto_config/processing.py, zabbix_auto_config/utils.py
Inventories to be managed by zac can be configured by config.ini.
=> Add ability to populate host inventory

zabbix_auto_config/processing.py
Fixes a missing variable update. Resolves #28 
This might lead to changes in Zabbix, if the bug has lead to hosts/hostgroups not being updated/removed properly.
=> Fix missing variable update

config.sample.ini, zabbix_auto_config/__init__.py, zabbix_auto_config/processing.py
Intended to fix #7
Adds a new config option `health_file`. This could point to a file, e.g: `/tmp/zac_health.json`.
At intervals the health file will contain something like this:
```json
{
"date": "2022-01-06T23:19:15",
"date_unixtime": 1641507555,
"pid": 2987176,
"cwd": "/home/zabbix/zabbix-auto-config",
"all_ok": true,
"processes": [
{
"name": "mysource",
"pid": 2987217,
"alive": true,
"ok": true
},
{
"name": "othersource",
"pid": 2987218,
"alive": true,
"ok": true
},
{
"name": "source-handler",
"pid": 2987219,
"alive": true,
"ok": true
},
{
"name": "source-merger",
"pid": 2987221,
"alive": true,
"ok": true
},
{
"name": "zabbix-host-updater",
"pid": 2987226,
"alive": true,
"ok": true
},
{
"name": "zabbix-hostgroup-updater",
"pid": 2987231,
"alive": true,
"ok": true
},
{
"name": …
```
=> Health data

zabbix_auto_config/processing.py
Fix another instance of `interface["foo"]`.
=> Fix interface type error.

zabbix_auto_config/__init__.py
This makes it possible to have dynamic triggers, e.g. `queue size >= failsafe`.
=> Write failsafe to health file.

tests/fixtures.py, tests/test_models.py, zabbix_auto_config/models.py
Most fields in the `Host` class have had their `Optional` type removed, and a new `"*"` validator has been added to ensure these fields can still be instantiated with `None` (ensuring backwards compatibility). The validator guarantees that these fields are _not_  `None` once the object itself has been instantiated, as it uses the field's default value or default factory to assign values to them.
Affected fields in `Host`:
- `interfaces`
- `inventory`
- `properties`
- `proxy_pattern`
- `siteadmins`
- `sources`
- `tags`
Furthermore, tests for `Host.merge()` as well as `Host.importance`**\*** have been added.
Since it's a bit unclear how `Host.proxy_pattern` and `Host.macros` should be handled when merging, they are not tested.
**\*** This probably could have been a separate pull request, …
=> Remove `Optional[]` types from `models.Host` fields & add tests

.github/workflows/test.yaml, tests/conftest.py, tests/test_config.py, tests/test_models.py
This pull request rewrites all `unittest.TestCase` tests as pytest tests and uses pytest as the test runner in CI.
* All `unittest.TestCase`-based tests have been rewritten as standalone `test_*` functions (pytest style).
* GitHub Actions workflow now runs the tests with pytest instead of unittest. 
* `tests/fixtures.py` renamed to `tests/conftest.py` so it is automatically imported by pytest.
* As a part of this, fixtures are now proper pytest fixtures.
* Fixtures are currently set to be function-scoped, which allows for modification of their return values without affecting other tests.
The existing tests already use pytest functionality such as `pytest.raises`. Furthermore, the other Zabbix project, zabbix-cli, already runs its tests via pytest instead of unittest. Since pytest is …
=> Rewrite Tests as Pytest Tests

docker-compose.yml
I noticed that the ports part is put on the wrong container. It should be moved to actually expose the database.
=> Fix misplaces ports in compose file

tests/conftest.py
The tests complain that:
```
tests/conftest.py:43
zabbix-auto-config/tests/conftest.py:43: DeprecationWarning: invalid escape sequence '\d'
"proxy_pattern": "^zbx-proxy\d+\.example\.com$",
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```
This makes it a raw string.
=> Fix missing raw string

tests/test_config.py, zabbix_auto_config/__init__.py, zabbix_auto_config/models.py
This pull request makes the config parsing less strict, and allows for passing in extra fields, which by default are ignored. Each extra field passed to the config is logged with a WARNING level. 
This makes it easier to use the same config file across different versions. Particularly if a config field is removed in the future, older versions of the config can still be used, and users are made aware of the removed fields with the generated warnings.
Given the following config with the two extra fields `zac.my_extra_field_zabbix` and `zabbix.my_extra_field_zabbix`:
```toml
[zac]
my_extra_field_zac = ["yeah"]
[zabbix]
my_extra_field_zabbix = true
```
The following logs are generated:
```
2023-03-15T15:26:09+0100 WARNING [MainProcess 36778] [root] ZacSettings: Got unknown config field …
```
=> Allow extra config fields and log warning for each extra field

setup.cfg
Pydantic v2 breaks a bunch of stuff which requires some non-trivial changes. Before we can fix that, we need to restrict the required version to be anything between 1.0.0 and 2.0.0 for now, so new installations of the application does not use >=2.0.0.
=> Require pydantic>=1.0.0,<2.0.0

zabbix_auto_config/__init__.py, zabbix_auto_config/processing.py, zabbix_auto_config/utils.py
Fixes #60 by draining the queue if new hosts are collected before the previous hosts in the queue have been consumed. To prevent future unbounded queue growth due to developer errors, the max size of these queues have been set to 1, which makes it explicit that these queues should never contain more than a single collection result at any point.
A warning log message is now generated when the collection rate outpaces the processing rate.
=> Prevent unbounded queue growth

tests/test_config.py, zabbix_auto_config/processing.py
This PR optimizes the processes of handling and merging hosts. By consolidating most DB transactions and performing bulk reads, handling hosts is up to 90x faster, while merging hosts is up to 60x faster.
Handling of source hosts has been optimized by fetching all hostnames in a single DB query and performing all work in a single transaction as opposed to one transaction per host.
When handling >13k hosts from 5 different sources, the following results were observed:
**Before**
```
[root] Done handling hosts from source, 'nivlheim', in 289.80 seconds. 
[root] Done handling hosts from source, 'mreg', in 104.38 seconds.
[root] Done handling hosts from source, 'nav', in 2.48 seconds.
[root] Done handling hosts from source, 'nav-ea', in 20.37 seconds.
```
**After**
```
[root] Done handling …
```
=> Optimize host merging and handling

setup.cfg, tests/test_config.py, tests/test_models.py, tests/test_processing/test_sourcecollectorprocess.py, zabbix_auto_config/__init__.py, zabbix_auto_config/models.py, zabbix_auto_config/processing.py
Pydantic v2 brings with it [much higher performance](https://docs.pydantic.dev/latest/blog/pydantic-v2-alpha/#headlines) (5-50x times faster than Pydantic v1), as well as improved APIs for validation and (de)serialization.
This PR bumps the minimum Pydantic version of ZAC to 2.0.0.  Code changes have been made to accommodate the new APIs introduced in 2.0.0. Most of the code changes were made using the migration tool [Bump Pydantic](https://github.com/pydantic/bump-pydantic) as outlined in the [Pydantic V2 Migration Guide](https://docs.pydantic.dev/latest/migration/). 
The use of `BaseSettings` has been substituted with `BaseModel` since we didn't use any of the features offered by `BaseSettings`. Furthermore, the `BaseSettings` class has been moved to the …
=> Migrate to Pydantic v2

config.sample.toml, tests/test_models.py, zabbix_auto_config/__init__.py, zabbix_auto_config/models.py, zabbix_auto_config/processing.py
This PR adds the ability to control the log level with the new config option `zac.log_level`:
```toml
[zac]
log_level = "DEBUG
```
While the log level technically can be specified as an integer (0, 10 ,20, etc.) it's not recommended.
This PR also fixes the problem of multiprocessing_logging causing an incredibly long traceback whenever the application is terminated, by calling `multiprocessing_logging.install_mp_handler()` _before_ the logger is configured.
=> Add configurable log level

config.sample.toml, setup.cfg, tests/test_models.py, tests/test_processing/test_sourcecollectorprocess.py, tests/test_processing/test_zabbixupdater.py, zabbix_auto_config/models.py, zabbix_auto_config/processing.py
This PR adds configurable timeouts for connecting and reading from the Zabbix API. This prevents the application from hanging from waiting indefinitely on HTTP requests that will never be answered by the API.
A new config option has been added to the `[zabbix]` table:
```toml
[zabbix]
timeout = 60
```
By default, the timeout is set to 60 seconds, but can be disabled by setting it to 0:
```toml
[zabbix]
timeout = 0
```
A new dev dependency [`pytest-timeout`](https://pypi.org/project/pytest-timeout/) has been added to facilitate testing of subprocesses. Its fixture `pytest.mark.timeout` simplifies termination of processes with no set end duration. It allows us to easily wait for certain conditions in the processes without fear of looping forever if the condition is not hit.
=> Add Zabbix API timeout

zabbix_auto_config/processing.py
This PR adds exception handling and subsequent termination when the two required host groups are missing. Previously this caused an unhandled `IndexError` exception due to the `ZabbixAPI.hostgroup.get` call returning an empty list.
```
2023-11-22T11:09:52+0000 CRITICAL [zabbix-host-updater 21006] [root] Disabled host group 'All-auto-disabled-hosts' does not exist in Zabbix. Cannot disable host 'foo.example.com'.
2023-11-22T11:09:52+0000 DEBUG [zabbix-host-updater 21006] [root] Told to stop. Breaking
```
```
2023-11-22T11:25:38+0000 CRITICAL [zabbix-host-updater 22867] [root] Enabled host group 'All-hosts' does not exist in Zabbix. Cannot enable host 'foo.example.com'
2023-11-22T11:25:38+0000 DEBUG [zabbix-host-updater 22867] [root] Told to stop. Breaking
```
=> Handle missing required host groups

config.sample.toml, zabbix_auto_config/models.py, zabbix_auto_config/processing.py
This PR adds the ability to signal approval of changes when the failsafe is hit by creating a temporary file in a location specified by the config option `zac.failsafe_ok_file`. If this file is detected, the application goes ahead and makes the changes. 
The file is always deleted after its detection, so that each approval requires the re-creation of this file. See #73 for more information on the considerations made when implementing this.
Closes #73
=> Approve failsafe with temp file

config.sample.toml, zabbix_auto_config/models.py, zabbix_auto_config/processing.py, zabbix_auto_config/utils.py
This PR adds the ability to configure whether or not the failsafe OK file must be deletable when approving changes. If the new `failsafe_ok_file_strict` option is set to `false`, the application will always go through with changes regardless of its ability to delete the file.
=> Toggle whether failsafe OK file must be deletable

README.md, config.sample.toml, pyproject.toml, tests/test_models.py, tests/test_version.py, zabbix_auto_config/models.py, zabbix_auto_config/processing.py
This PR introduces the ability to automatically create template groups for all managed host groups. Two new configuration options have been introduced to facilitate this:
```toml
[zabbix]
create_templategroups = false
templategroup_prefix = "Templates-"
```
On Zabbix <6.2, this feature will create the template groups as host groups instead.
The feature is disabled by default.
The `BaseProcess` class now fetches the Zabbix API version ([always matches the Zabbix Server version](https://www.zabbix.com/documentation/current/en/manual/api/reference/apiinfo/version)) on instantiation and stores it in the attribute `self.zabbix_version`, which allows each process to perform version checks without having to add boilerplate code for fetching and parsing version numbers first. The version is …
=> Add template group creation

pyproject.toml, tests/test_models.py, zabbix_auto_config/processing.py, zabbix_auto_config/utils.py
This PR adds Ruff linting rules for finding incorrect usage of standard library logging.
Adds the following rules:
- `G` (flake8-logging-format)
- `LOG` (flake8-logging)
- `PLE1205` (pylint: too many logging args)
- `PLE1206` (pylint: too few logging args).
=> Add Ruff logging rules

README.md, tests/test_failsafe.py, tests/test_utils.py, zabbix_auto_config/__init__.py, zabbix_auto_config/_types.py, zabbix_auto_config/compat.py, zabbix_auto_config/failsafe.py, zabbix_auto_config/models.py, zabbix_auto_config/processing.py, zabbix_auto_config/state.py, zabbix_auto_config/utils.py
This PR adds Zabbix 7.0 compatibility. There are numerous API changes in 7.0, for which a new `compat.py` module has been added.  This module adds functions that take in the current Zabbix API version and return the correct API method parameter / object property name.
The current implementation is a bit messy, and we will have to consider if we want to refactor all the API calls. Constructing large parameter dicts inline leads to some readability issuses, which we should try to mitigate. It's already kind of overloaded with long names and such.
=> Add Zabbix 7.0 compatibility

config.sample.toml, pyproject.toml, zabbix_auto_config/__init__.py, zabbix_auto_config/models.py, zabbix_auto_config/processing.py, zabbix_auto_config/pyzabbix/client.py
This PR changes the log level of some informative log messages from DEBUG to INFO, so that switching log level from DEBUG to INFO does not cause a loss of important information about the state of the application.
This turns DEBUG logging into something that makes more sense to opt into for full introspection of the application's internal decision making process when required, but not something that should be enabled by default. The new default is INFO.
=> Change log statement levels, change default level to INFO

zabbix_auto_config/processing.py, zabbix_auto_config/pyzabbix/client.py, zabbix_auto_config/pyzabbix/types.py
This PR aims to reduce the memory usage after #81, which introduced Pydantic models for all API objects.
The PR makes the following adjustments:
- No longer uses `"output": "extend"` for many API methods, reducing the amount of data we fetch.
- Made `ZabbixAPI.get_hosts()` into a generator of `Host` objects instead of using a list comprehension to return a list.
- Removed redundant calls to `.keys()` on large dicts
=> Optimize memory usage

zabbix_auto_config/exceptions.py, zabbix_auto_config/processing.py, zabbix_auto_config/pyzabbix/client.py, zabbix_auto_config/pyzabbix/types.py
This PR adds handling for expired API user sessions by adding automatic attempts to re-login to the API.
The implementation isn't super clean; `isinstance(self, ZabbixUpdater)` is not _great_, but the alternatives are all more time-consuming and error prone. This works fine.
Also adds/removes some miscellaneous comments.
Closes #88
=> Re-login on expired session

README.md, pyproject.toml, tests/test_config.py, zabbix_auto_config/models.py
This PR adds a computed default for a source collector's `error_duration` based on its `update_interval` and `error_tolerance`. 
Given a the following config, we can expect ZAC to compute a default value for `error_duration` that is between 300 and 359 seconds:
```toml
[source_collectors.faultysource]
module_name = "faultysource"
update_interval = 60
error_tolerance = 5
exit_on_err = false
```
This PR uses the following formula to compute the default value: `round(error_tolerance * update_interval + (update_interval*0.9))`. So for the config above, we will get a default `error_duration` of 354.
The extra duration (`update_interval*0.9`) allows for some accumulated latency during and between updates, while still ensuring 5 _successive_ errors are required to trigger deactivation.
=> Compute default error duration if omitted

CHANGELOG.md, README.md, config.sample.toml, tests/test_config.py, tests/test_models.py, zabbix_auto_config/models.py, zabbix_auto_config/processing.py
This PR implements more sensible failure strategy defaults for source collector errors. The following is changed:
1. The error tolerance stuff is now opt-in by default.
2. The default strategy for source collector errors is now to apply a delay using exponential backoff to the source's update interval on failure.
3. `exit_on_error` is now `False` by default, and must be opted in to. The default behavior is now to use the backoff strategy outlined above. This is technically a breaking change, as failing sources would terminate the application prior to this PR.
All in all, this PR brings in more sensible error handling defaults for source collectors and makes the application more likely to recover from intermittent errors.
=> Add update interval exponential backoff on source collector failure

tests/test_state.py, tests/test_utils.py, zabbix_auto_config/processing.py, zabbix_auto_config/state.py, zabbix_auto_config/utils.py
This PR improves the heuristics for determining when to warn about a too-short update interval for processes.
It requires the following conditions to be satisfied before issuing a warning for the process:
1. Update interval is not 0
2. Work duration exceeds update interval
3. Has not warned within the last hour
To facilitate this, the `State` class has been expanded with tracking of execution metrics for each process.
=> Improve interval too short warnings

tests/test_health.py, tests/test_state.py, zabbix_auto_config/__init__.py, zabbix_auto_config/_types.py, zabbix_auto_config/health.py, zabbix_auto_config/state.py
Fixes health file failing to serialize to JSON with the new `State` fields introduced in #93. 
This PR also rewrites the following as Pydantic models for easier and more consistent JSON serialization:
- Health file
- State
=> Refactor health file

.github/workflows/test.yaml, README.md, pyproject.toml
=> Drop Python 3.8 support

.github/workflows/test.yaml, README.md, config.sample.toml, pyproject.toml, uv.lock
Moves dependency management to uv lock file with dependency groups. No longer requires users to use Hatch for project management.
=> Use uv lock file

pyproject.toml, tests/conftest.py, tests/test_config.py, tests/test_errcount.py, tests/test_failsafe.py, tests/test_health.py, tests/test_models.py, tests/test_processing/test_sourcecollectorprocess.py, tests/test_processing/test_zabbixupdater.py, tests/test_state.py, tests/test_utils.py, zabbix_auto_config/models.py, zabbix_auto_config/processing.py, zabbix_auto_config/pyzabbix/client.py, zabbix_auto_config/pyzabbix/enums.py, zabbix_auto_config/pyzabbix/utils.py
Adds E, W, C4, and B rules. Enables experimental docstring formatting.
Fixes all rule violations stemming from the newly activated rules.
=> Ruff rules overhaul

zabbix_auto_config/models.py, zabbix_auto_config/processing.py, zabbix_auto_config/pyzabbix/client.py
Adds the ability to enable/disable SSL verification, as well as provide a path to a custom CA bundle in the configuration file.
```toml
[zabbix]
verify_ssl = "/path/to/certs.pem" # or True/False
```
The default value is `True`, which reflects the current client defaults.
=> Add SSL verification configuration

CHANGELOG.md, zabbix_auto_config/errcount.py, zabbix_auto_config/models.py, zabbix_auto_config/pyzabbix/client.py
Also fixes a bunch of minor bugs
=> Use `Path` type for `zabbix.verify_ssl`, fix `timeout`

zabbix_auto_config/processing.py
Refactors the failure strategy handler selection to make it easier to add and remove strategies. It also removes a level of nested conditionals, which makes the code easier to reason about.
Finally, when there _is_ a method to handle the error, but the error tolerance is not yet reached, a debug logging call is added to signal that we received the error, but did not take action.
=> Refactor failure strategy handler selection

zabbix_auto_config/sourcecollectors.py
Raising a ZACException containing the Pydantic error message is enough information to debug the problem. Raising from the original ValidationError creates a very long stack trace containing the same Pydantic error message twice. Example:
```
Traceback (most recent call last):
File "/home/zabbix-local-test/zabbix-auto-config/zabbix_auto_config/sourcecollectors.py", line 44, in from_kwargs
return cls.model_validate(kwargs)
File "/home/zabbix-local-test/zabbix-auto-config/venv/lib64/python3.9/site-packages/pydantic/main.py", line 596, in model_validate
return cls.__pydantic_validator__.validate_python(
pydantic_core._pydantic_core.ValidationError: 2 validation errors for LDAPConfig
properties
Set should have at least 1 item after validation, not 0 [type=too_short, input_value=[], …
```
=> Don't raise from ValidationError on failed CollectorConfig validation

zabbix_auto_config/processing.py
Attempts to resolve #113 by consolidating the 3 transactions in `SourceMerger.merge_hosts()` into a single transaction.
Furthermore, host deletion is now done as a bulk operation instead of deleting each host sequentially:
https://github.com/unioslo/zabbix-auto-config/blob/71b0180f84cac20fb638fc660c749ed5ec184f9a/zabbix_auto_config/processing.py#L686-L691
As a final measure against deadlocks, `SELECT ... FOR UPDATE` is used when fetching hosts from the merged hosts table, so we lock the rows we are updating:
https://github.com/unioslo/zabbix-auto-config/blob/159564b230e5215bcfb9ad276721f26840a5cd6b/zabbix_auto_config/processing.py#L675-L679
=> Consolidate and simplify transactions to combat deadlocks

CHANGELOG.md, README.md, pyproject.toml, uv.lock, zabbix_auto_config/__init__.py, zabbix_auto_config/config.py, zabbix_auto_config/dirs.py
Adds support for loading the config file from `XDG_CONFIG_HOME` via platformdirs.
=> Add XDG base dir support for config file

pyproject.toml, tests/conftest.py, tests/test_config.py, tests/test_failsafe.py, tests/utils.py, uv.lock, zabbix_auto_config/__init__.py, zabbix_auto_config/__main__.py, zabbix_auto_config/config.py, zabbix_auto_config/exceptions.py, zabbix_auto_config/models.py
Adds a CLI interface to ZAC for overriding some common config options, or specifying a new config path entirely.
```
❯ zac --help
Usage: zac [OPTIONS]                                                                               
Run Zabbix-auto-config.                                                                            
╭─ Options ────────────────────────────────────────────────────────────────────────────────────────╮
│ --failsafe  -F      INTEGER  Maximum number of hosts to change.                                  │
│ --dryrun    -D               Dry run mode.                                                       │
│ --config    -C      PATH     Path to config file.                                                │
│ --help                       Show this message and exit. …
```
=> Add Typer CLI

pyproject.toml, tests/test_utils.py, uv.lock, zabbix_auto_config/utils.py
Ensures mapping file entries such as the following are handled:
```
key: value # inline comment for the line here
```
Furthermore, add ruff as a dev dependency so automatic formatting of snapshots actually works.
=> Handle trailing comments in mapping file

tests/test_errcount.py
The timing for this test was too tight, which caused it to be flaky.
=> Fix flaky error counter test
